apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: pypi-proxy-scan-fqdn
  namespace: monitoring
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - fqdns:
      - slack.com
      - hooks.slack.com
  podSelector:
    matchLabels:
      app: pypi-proxy-scan
  policyTypes:
  - Egress
