apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pypi-proxy-scan
  namespace: monitoring
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 151.101.0.0/16 # pypi
  podSelector:
    matchLabels:
      app: pypi-proxy-scan
  policyTypes:
  - Egress
